export const initialDataClients = [
  {
    key: '1',
    name: 'Иван',
    lastName: 'Иванов',
    middleName: 'Иванович',
    phone: '89002500163',
    email: 'ivan@gmail.com',
    adress: 'Набережная 24',
  },
  {
    key: '2',
    name: 'Дмитрий',
    lastName: 'Орджоникидзе',
    middleName: 'Станиславович',
    phone: '89032500163',
    email: 'dmitry@gmail.com',
    adress: 'Кружевная 789',
  },
  {
    key: '3',
    name: 'Артем',
    lastName: 'Ситников',
    middleName: 'Дамирович',
    phone: '89102500163',
    email: 'artem@gmail.com',
    adress: 'Вишнякова 432',
  },
  {
    key: '4',
    name: 'Марк',
    lastName: 'Сергеев',
    middleName: 'Юлианович',
    phone: '89022500163',
    email: 'mark@gmail.com',
    adress: 'Гуляева 24',
  },
  {
    key: '5',
    name: 'Анна',
    lastName: 'Кремова',
    middleName: 'Сергеевна',
    phone: '89003500163',
    email: 'anna@gmail.com',
    adress: 'Прибрежная 24',
  }
]